### ISSUE TITLE
Add Support for Image Digest in Helm Chart

### ISSUE THREAD

**Issue by Zarmbinski** [newrelic/nri-kube-events#136]
## Summary

In addition to allowing the consumer to supply a specific image tag and registry, it should also be possible to specify an image SHA.

## Desired Behaviour

When a user specifies an image digest in their `values.yaml` file:
```yaml
images:
  agent:
    digest: sha256:abc123def456
```
This SHA should be used to identify which image is used. In the event that the tag *and* the SHA are supplied, the `SHA` will take precedence

## Possible Solution

The new value should be added as an option in the `values` file under `images.[agent/integration].digest`, and the image string produced and placed in the resulting manifest will feature the full image name (including the `@` or `:` delimiter).

## Additional context

We are requesting this feature in order to allow [Cosign](https://github.com/sigstore/cosign) (our image signing/verification system) to process the images included within this chart. In order for Cosign to function properly, the image digest must be used in the kubernetes manifest. While Cosign does have a mutating webhook configuration that has the ability to sub-in the SHA for the tag, this causes a bad situation when coupled with GitOps tools like ArgoCD, so we still need to be able to supply the chart with a specific image SHA.

**Comment by sigilioso** [comment]
Hi @Zarmbinski, thanks for opening the issue! We are taking a look at it, we will analze and get is prioritized as soon as possible.

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
