### ISSUE TITLE
Bug - Unused prop `podLabels` in `values.yaml`

### ISSUE THREAD

**Issue by josephmcasey** [newrelic/nri-kube-events#142]
https://github.com/newrelic/nri-kube-events/blob/648c35b59ffe44d121cb6a31bf6c9c96113b849b/charts/nri-kube-events/values.yaml#L66

### Context
While looking over the documentation I noticed that it looked like one of the props for the helm chart was unused.

### Problem Statement:
It seems as if there is a `podLabels` that is documented in the [`README.md`](https://github.com/newrelic/nri-kube-events/blob/main/charts/nri-kube-events/README.md?plain=1#L59) and set as a value in the [`values.yaml`](https://github.com/newrelic/nri-kube-events/blob/648c35b59ffe44d121cb6a31bf6c9c96113b849b/charts/nri-kube-events/values.yaml#L66)?

### Recommendation:

Either of the following solutions could be used:

1. Use the `"newrelic.common.labels.podLabels"` helper function from [common library v1.06 dependency](https://github.com/newrelic/helm-charts/blob/common-library-1.0.6/library/common-library/templates/_labels.tpl#L40-L54) in the following to [charts/nri-kube-events/templates/deployment.yaml#L23](https://github.com/newrelic/nri-kube-events/blob/main/charts/nri-kube-events/templates/deployment.yaml#L16-L23)
```
        {{- include "newrelic.common.labels.podLabels" . |  nindent 8 -}}
```

2. Remove [`README.md#L59`](https://github.com/newrelic/nri-kube-events/blob/main/charts/nri-kube-events/README.md?plain=1#L59) and [`values.yaml#L66`](https://github.com/newrelic/nri-kube-events/blob/648c35b59ffe44d121cb6a31bf6c9c96113b849b/charts/nri-kube-events/values.yaml#L66)

**Comment by kang-makes** [comment]
Hi!

Thanks for raising this issue, we took some time and we saw that this also affects other charts, so we are going to do the follow-up of all the charts in this issue. This is the list of affected charts: 
 - [ ] `nri-kube-events`: https://github.com/newrelic/nri-kube-events/blob/9d4e226/charts/nri-kube-events/templates/deployment.yaml#L23
 - [ ] `newrelic-k8s-metrics-adapter`: https://github.com/newrelic/newrelic-k8s-metrics-adapter/blob/fc87009/charts/newrelic-k8s-metrics-adapter/templates/deployment.yaml#L22
 - [ ] `newrelic-infra-operator`: https://github.com/newrelic/newrelic-infra-operator/blob/a945b9a/charts/newrelic-infra-operator/templates/deployment.yaml#L22
 - [ ] `k8s-metadata-injection`: https://github.com/newrelic/k8s-metadata-injection/blob/8b6ee3a/charts/nri-metadata-injection/templates/deployment.yaml#L22
 
 We have started to work on this.

**Comment by kang-makes** [comment]
Sorry for the noise closing and reopening the issue. The "Solves" comment in the PRs closed automatically this issue.

Everything is merged. Is a matter of time that the PR of renovatebot hit `nri-bundle` to be available to the public :)
