### ISSUE TITLE
An host entity is created for each kube-event-pod

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kube-events#25]
Currently an entity is created when a kube-event is deployed.
This is not the expected behaviour, since the infra sidecar is used as a forwarder only.

We should investigate if the behaviour changed in the latests version or we always had this issue even setting `NRIA_IS_FORWARD_ONLY=true` and `NRIA_IS_SECURE_FORWARD_ONLY=true`

![Screen Shot 2021-03-17 at 11 59 27 AM](https://user-images.githubusercontent.com/43335750/111457240-3bf7ea00-8718-11eb-99e5-c0893964841b.png)

**Comment by paologallinaharbur** [comment]
Context on the entity creation:
 -  https://docs.google.com/document/d/1zuyMPlhLDG6aZXSP2PCQ8x5FMCJQrA0_Gf8S4Kb-Hvo/edit#

**Comment by varas** [comment]
Entity creation should be disabled via `connect_enabled: false` see https://github.com/newrelic/infrastructure-agent/blob/30d0e84f3526ab0e1398d7908cc6e73193a21109/pkg/config/config.go#L885-L890

**Comment by kang-makes** [comment]
This is fixed. And the custom attributes issue that this change raised is fixed too.

Closing
