### ISSUE TITLE
Add filtering options for "event.type" in config settings

### ISSUE THREAD

**Issue by thezackm** [newrelic/nri-kube-events#5]
## Summary

Please enhance the configuration options for this integration to include filtering out `event.type = 'Normal'` events.

## Desired Behavior

Options in both YAML manifest and helm deployment methods that allow users to limit event collection to only `event.type = 'Warning'` events

## Additional context

'Normal' events can be very verbose and end up being unnecessary for collection as they aren't helpful in troubleshooting. It makes sense to provide options to adjust collection for various situations, such as lower-environment k8s clusters where 100% data collection is not required or fiscally conservative.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
