### ISSUE TITLE
Add curl to the docker image

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/nri-kube-events#54]
- Add the curl command to the docker image

**Comment by paologallinaharbur** [comment]
@alvarocabanas 
There was also this issue https://github.com/newrelic/infrastructure-agent/pull/530 that added it to the base image of the sidecar. For that image a version bump is enough 😄

**Comment by gsanchezgavier** [comment]
I don't think this is needed since the event-forwarder sidecar (infra-agent) already have it from 1.19 and that should be the container used for troubleshooting with curl
