### ISSUE TITLE
Events timestamp appears to be the reporting timestamp and not the actual event timestamp

### ISSUE THREAD

**Issue by fgimenezm** [newrelic/nri-kube-events#6]
## Description

This comes from the forums: [Latest() not returning the actual latest](https://discuss.newrelic.com/t/latest-not-returning-the-actual-latest/113509/1)

I’m trying to create a NRQL query that returns the latest node status in a k8s cluster based on the NodeReady and NodeNotReady events.
The closest I got to that is:

`SELECT latest(event.reason) from InfrastructureEvent where event.reason in (‘NodeNotReady’,‘NodeReady’) facet event.involvedObject.name since 356 days ago`

But sometimes it returns “NodeNotReady” for nodes that are actually ready and if I query the node specific data I can see the latest event.reason is indeed “NodeReady” when sorted by event.lastTimestamp.

I’m attaching a few screenshots filtered for a specific node that was showing this behavior a few minutes ago. I’ve highlighted some areas that I think will help clarify the issue.

If for some reason the screenshots don't show up here, please check the forum post where I shared them originally.

Query showing the “NodeNotReady” result for a node that is Ready:

![](https://nr-production-discourse.s3.dualstack.us-east-1.amazonaws.com/original/3X/c/5/c5ec24fc7e2170230303503e5ffa7e0444eeba89.png)

Another query showing the NodeReady and NodeNotReady events for that same node with default sorting. Note that the two most recent events have the same timestamp but their event.lastTimetamp differs:

![](https://nr-production-discourse.s3.dualstack.us-east-1.amazonaws.com/original/3X/f/f/ffeaeab0c1e7686c099004326ce8f494534728b8.png)

And the same query sorted by event.lastTimestamp desc:

![](https://nr-production-discourse.s3.dualstack.us-east-1.amazonaws.com/original/3X/d/d/dd820e004e39781e09b2eea9c9312132609da089.png)

## Steps to Reproduce

I executed the query on two clusters and both returned "NodeNotReady" for some nodes that had a more recent "NodeReady" event. This appears to be related to how the timestamp for the events is handled when reporting them.

## Expected Behaviour

The latest() event should be the one that happened last.

## Relevant Logs / Console output

Screenshots are available in the forum: [Latest() not returning the actual latest](https://discuss.newrelic.com/t/latest-not-returning-the-actual-latest/113509/1)

## Your Environment

Openshift 3.11.248
infrastructure-k8s:1.26.2
k8s-events-forwarder:1.12.0

**Comment by josemore** [comment]
Thanks for reporting this @fgimenezm 
I wanted to add that the infra agent added support for integrations to overwrite the default timestamp (https://github.com/newrelic/infrastructure-agent/pull/29) so this might require an update to send the proper value.

**Comment by fgimenezm** [comment]
@josemore , I'm new to Go language but I'm guessing this could be done around [here](https://github.com/newrelic/nri-kube-events/blob/f597f3d025aad006b05b690fde85aeac24bde341/pkg/events/router.go#L134) 
or maybe [here](https://github.com/newrelic/nri-kube-events/blob/f597f3d025aad006b05b690fde85aeac24bde341/pkg/events/router.go#L144)
Or perhaps at the sink itself somewhere in the HandleEvent method [here](https://github.com/newrelic/nri-kube-events/blob/f597f3d025aad006b05b690fde85aeac24bde341/pkg/sinks/new_relic_infra.go#L119)

What do you recommend?

**Comment by weemel** [comment]
Hi @josemore, @fgimenezm, I've double-posted this in the forum chat as well - I'm wondering if the issue is actually that New Relic timestamps only record up to the second, rather than millisecond? We send logs to Elasticsearch and the logs for kube-events look like this for one example:

```
Elasticsearch timestamp     New Relic Event log
Jan 6, 2021 @ 09:53:04.229	time="2021-01-06T09:53:04Z" ... ,\"reason\":\"Starting\", ...
Jan 6, 2021 @ 09:53:04.159	time="2021-01-06T09:53:04Z" ... ,\"reason\":\"NodeNotSchedulable\", ...
Jan 6, 2021 @ 09:53:04.158	time="2021-01-06T09:53:04Z" ... \"reason\":\"NodeReady\", ...
Jan 6, 2021 @ 09:53:04.158	time="2021-01-06T09:53:04Z" ... \"reason\":\"NodeHasNoDiskPressure\", ...
Jan 6, 2021 @ 09:53:04.158	time="2021-01-06T09:53:04Z" ... \"reason\":\"NodeHasSufficientPID\", ...
Jan 6, 2021 @ 09:53:04.158	time="2021-01-06T09:53:04Z" ... \"reason\":\"NodeHasSufficientMemory\", ...
Jan 6, 2021 @ 09:53:04.147	time="2021-01-06T09:53:04Z" ... \"reason\":\"Rebooted\", ...
Jan 6, 2021 @ 09:53:04.147	time="2021-01-06T09:53:04Z" ... \"reason\":\"NodeAllocatableEnforced\", ...
Jan 6, 2021 @ 09:53:04.145	time="2021-01-06T09:53:04Z" ... \"reason\":\"NodeHasNoDiskPressure\", ...
Jan 6, 2021 @ 09:53:04.145	time="2021-01-06T09:53:04Z" ... \"reason\":\"NodeHasSufficientMemory\", ...
Jan 6, 2021 @ 09:53:04.145	time="2021-01-06T09:53:04Z" ... \"reason\":\"NodeHasSufficientPID\", ...
Jan 6, 2021 @ 09:53:04.145	time="2021-01-06T09:53:04Z" ... \"reason\":\"Starting\", ...
Jan 6, 2021 @ 09:53:04.134	time="2021-01-06T09:53:04Z" ... \"reason\":\"NodeNotReady\", ...
Jan 6, 2021 @ 09:51:19.617	time="2021-01-06T09:51:19Z" ... \"reason\":\"NodeNotSchedulable\", ...
```

The NodeReady event is recorded at 09:53:04.158 while the NodeNotReady event is at 09:53:04.134 - milliseconds’ difference. It seems to me that this detail is lost in New Relic so presumably the latest() of the two would randomly be either one or the other. In this case I get “NodeNotReady” as the latest(), similarly to the original poster.

If my reasoning is correct, would it possible to get the millisecond resolution too? I guess one way might be to insert the unix timestamp as another attribute/column if the existing set up is not possible.

Many thanks
Mel

**Comment by davidgit** [comment]
Closing this issue as stale. Please reopen this issue and PR when you are ready to retake a look at it. 

Thank you for your contribution!
