### ISSUE TITLE
custom_attributes are not decorated into the payload emitted

### ISSUE THREAD

**Issue by kang-makes** [newrelic/nri-kube-events#85]
## Description

This is to follow the issue newrelic/infrastructure-agent#911

The agent should decorate all the data emitted by itself with the custom attributes while in forward only mode. 

We find out that it decorates everything in V4 format and only metrics in V3. As this integration emits events in V3 format they are not decorated properly.

**Comment by paologallinaharbur** [comment]
Removing it from the epic, since it is not connected

**Comment by davidgit** [comment]
New [release](https://github.com/newrelic/infrastructure-agent/releases/tag/1.23.2) of the infra agent including decorate events with custom_attributes https://github.com/newrelic/infrastructure-agent/pull/939

**Comment by kang-makes** [comment]
Closed with the release of newrelic/helm-charts#598
